# define pipeline number (https://docs.microsoft.com/en-us/azure/devops/pipelines/build/options?view=azure-devops&tabs=yaml#build-number-format)
name: 1.0$(Rev:.r)

# define resources (https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example#repository-resource)
resources:
  repositories:
    - repository: templates
      type: github
      name: kbrashears5/yaml
      endpoint: kbrashears5

# define variable groups (https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml#use-a-variable-group)
variables:
  - group: github

# define build triggers (https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=example#trigger)
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - src/*
      - package.json

# define pull request triggers (https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#pr-triggers)
pr:
  autoCancel: true
  branches:
    include:
      - master
  paths:
    include:
      - src/*
      - package.json

# build and create npm package
stages:
  - template: templates/build-node.yml@templates
    parameters:
      pack: true
