name: Release Maker

on:
  repository_dispatch:
    types:
      - release

jobs:
  release_maker:
    runs-on: ubuntu-latest
    steps:
      - name: Release Maker
        uses: kbrashears5/github-action-release-maker@master
        with:
          VERSION: ${{ github.event.client_payload.version }}
          TOKEN: ${{ secrets.ACTIONS }}